# Generated by Django 5.2.5 on 2025-10-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_context_window_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.DeleteModel(
            name='ConversationMemory',
        ),
    ]
